(()=>{'use strict';
const $=id=>document.getElementById(id),fmt=(v,d=0)=>new Intl.NumberFormat('de-CH',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v),chf=v=>`CHF ${fmt(v,2)}`,esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=v=>v!==''&&Number.isFinite(Number(String(v).replace(/[’'\s]/g,'')))&&Number(String(v).replace(/[’'\s]/g,''))>=0?Number(String(v).replace(/[’'\s]/g,'')):null;
let mode='internal2',demo=false;
const mix=[{name:'Schweizer Debitkarten',share:'65',ic:'0.20',scheme:'0.12'},{name:'Schweizer Kreditkarten',share:'25',ic:'0.40',scheme:'0.15'},{name:'Europäische Karten',share:'7',ic:'0.65',scheme:'0.30'},{name:'Übrige / Geschäftskarten',share:'3',ic:'1.50',scheme:'0.70'}];
const make=(name,provider='Nexi',model='blended')=>({name,provider,model,rate:'',txFee:'0',rent:'0',terminals:'1',monthly:'0',annual:'0',setup:'0',minimum:'0',surcharge:'0'});
const nexi=[make('Nexi mit Terminalmiete'),make('Nexi ohne Terminalmiete'),make('Nexi Verbandsangebot','Nexi','icpp')],competitor=make('Angebot des Wettbewerbers','Wettbewerber');
const offers=()=>mode==='competitor'?[nexi[0],competitor]:mode==='internal3'?nexi:nexi.slice(0,2);
const field=(label,key,value,unit,step='0.01')=>`<label>${label}<span class="control"><input data-key="${key}" type="number" min="0" step="${step}" inputmode="decimal" value="${esc(value)}"><b>${unit}</b></span></label>`;
function renderMix(){ $('mix').innerHTML=mix.map((m,i)=>`<div class="mix-row"><strong>${esc(m.name)}</strong>${field('Anteil',`share:${i}`,m.share,'%','0.1')}${field('Interchange',`ic:${i}`,m.ic,'%','0.001')}${field('Netzwerkgebühr',`scheme:${i}`,m.scheme,'%','0.001')}</div>`).join('');$('mix').oninput=e=>{const [key,i]=(e.target.dataset.key||'').split(':');if(key){mix[+i][key]=e.target.value;calculate();}};}
function card(o,i){const isCompetitor=o===competitor;return `<article class="offer ${isCompetitor?'competitor':''}" data-index="${i}"><div class="offer-heading"><span class="provider-tag">${isCompetitor?'WETTBEWERB':'NEXI'}</span><span>Option ${i+1}</span></div><label>Bezeichnung<input class="plain" data-key="name" maxlength="60" value="${esc(o.name)}" placeholder="z. B. Angebot mit Miete"></label><div class="model-toggle" role="group" aria-label="Preismodell für ${esc(o.name)}"><button type="button" data-model="blended" aria-pressed="${o.model==='blended'}">Ein Preis (Blended)</button><button type="button" data-model="icpp" aria-pressed="${o.model==='icpp'}">IC++</button></div><p class="model-explain">${o.model==='icpp'?'Deine Marge plus Karten- und Netzwerkgebühren.':'Ein vereinbarter Prozentsatz für die Kartenannahme.'}</p><div class="fields card-primary">${field(o.model==='icpp'?'Nexi-/Anbieter-Marge':'Gebühr pro Zahlung (Disagio)','rate',o.rate,'%','0.001')}${field('Terminalmiete pro Monat','rent',o.rent,'CHF')}</div><details class="cost-details"><summary>Weitere Kosten eintragen <span>optional</span></summary><div class="fields">${field('Fixgebühr je Zahlung','txFee',o.txFee,'CHF')}${field('Anzahl Terminals','terminals',o.terminals,'Stk.','1')}${field('Weitere Monatskosten','monthly',o.monthly,'CHF')}${field('Weitere Jahreskosten','annual',o.annual,'CHF')}${field('Einmalige Einrichtung','setup',o.setup,'CHF')}${field('Zusätzlicher prozentualer Zuschlag','surcharge',o.surcharge,'%','0.001')}${field('Mindestgebühr Acquiring / Monat','minimum',o.minimum,'CHF')}</div><p class="subtle">Nur Kosten erfassen, die tatsächlich zusätzlich anfallen. Eine Mindestgebühr ersetzt tiefere Acquiring-Kosten.</p></details><div class="offer-total" id="total-${i}"></div></article>`;}
function renderOffers(){ $('offers').classList.toggle('three-offers',mode==='internal3');$('offers').innerHTML=offers().map(card).join('');$('offers').querySelectorAll('.offer').forEach((node,i)=>{const o=offers()[i];node.addEventListener('input',e=>{const key=e.target.dataset.key;if(key){o[key]=e.target.value;calculate();}});node.querySelectorAll('[data-model]').forEach(button=>button.onclick=()=>{o.model=button.dataset.model;renderOffers();calculate();});});$('mix-setting').hidden=!offers().some(o=>o.model==='icpp');}
function cost(o,c,v=c.volume){const tx=v*c.tx/c.volume,acquiring=v*(+o.rate+(o.model==='icpp'?c.pass*100:0))/100+tx*+o.txFee,minimum=Math.max(0,+o.minimum*12-acquiring),surcharge=v*+o.surcharge/100,terminal=12*+o.rent*+o.terminals,other=12*+o.monthly+(+o.annual),once=+o.setup/c.years;return {acquiring,minimum,surcharge,terminal,other,once,total:acquiring+minimum+surcharge+terminal+other+once};}
function calculate(){const current=offers(),c={volume:num($('volume').value),tx:num($('tx').value),years:num($('years').value)},share=mix.reduce((v,m)=>v+(num(m.share)||0),0);c.pass=mix.reduce((v,m)=>v+(num(m.share)||0)/100*((num(m.ic)||0)+(num(m.scheme)||0))/100,0);c.mixValid=Math.abs(share-100)<.001&&mix.every(m=>['share','ic','scheme'].every(k=>num(m[k])!==null));$('mix-status').textContent=`${fmt(share,1)} % des Umsatzes zugeordnet`;$('mix-error').textContent=c.mixValid?'':'Bitte Kartenanteile auf 100 % verteilen und alle Gebührensätze eintragen.';$('ticket').textContent=c.volume>0&&c.tx>0?`Das entspricht durchschnittlich ${chf(c.volume/c.tx)} pro Kartenzahlung.`:'';
const keys=['rate','txFee','rent','terminals','monthly','annual','setup','minimum','surcharge'],ready=c.volume>0&&c.tx>0&&Number.isInteger(c.tx)&&Number.isInteger(c.years)&&c.years>=1&&c.years<=10&&(!current.some(o=>o.model==='icpp')||c.mixValid)&&current.every(o=>o.name.trim()&&keys.every(k=>num(o[k])!==null)&&Number.isInteger(+o.terminals));$('message').hidden=ready;$('result').hidden=!ready;$('print').disabled=!ready;if(!ready){$('message').textContent=current.some(o=>o.model==='icpp')&&!c.mixValid?'Prüfe bitte den Kartenmix unter „Weitere Annahmen ändern“.':'Trage für jede Option den Prozentsatz der Zahlungsgebühr ein. Die Terminalmiete kannst du bei Bedarf ändern.';current.forEach((o,i)=>{$(`total-${i}`).textContent='Ergebnis erscheint nach Eingabe des Prozentsatzes';});return;}
const ranked=current.map((o,i)=>({o,i,r:cost(o,c)})).sort((a,b)=>a.r.total-b.r.total);current.forEach((o,i)=>{$(`total-${i}`).innerHTML=`<span>Gesamtkosten pro Jahr</span><strong>${chf(cost(o,c).total)}</strong>`;});$('winner').textContent=ranked[0].o.name;$('saving').textContent=`${chf(ranked[0].r.total)} pro Jahr · ${chf(ranked[1].r.total-ranked[0].r.total)} günstiger als die nächstbeste Option`;
const max=Math.max(1,...ranked.map(x=>x.r.total));$('ranking').innerHTML=ranked.map((x,i)=>`<div class="rank"><div class="rank-line"><div><b>${esc(x.o.name)}</b><small>${x.o.provider} · ${x.o.model==='icpp'?'IC++':'Blended'}</small></div><strong>${chf(x.r.total)} / Jahr</strong></div><div class="bar-bg"><div class="bar ${i?'secondary':''}" style="width:${Math.max(2,x.r.total/max*100)}%"></div></div></div>`).join('');
$('breakdown').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Kosten pro Jahr</th>${ranked.map(x=>`<th>${esc(x.o.name)}</th>`).join('')}</tr></thead><tbody>${[['Kartenzahlungen','acquiring'],['Mindestgebühr (Aufpreis)','minimum'],['Zusätzliche Zuschläge','surcharge'],['Terminalmiete','terminal'],['Weitere laufende Kosten','other'],['Einrichtung, anteilig','once'],['Gesamt','total']].map(([label,k])=>`<tr><td>${label}</td>${ranked.map(x=>`<td>${chf(x.r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const sampled=[.25,.5,.75,1,1.5,2,3,5].map(k=>Math.max(1000,Math.round(c.volume*k/1000)*1000)),switches=sampled.map(v=>({v,o:[...current].sort((a,b)=>cost(a,c,v).total-cost(b,c,v).total)[0]})).filter((x,i,a)=>!i||x.o!==a[i-1].o);$('thresholds').innerHTML=`<p class="subtle">Bei gleichem Kartenmix und gleichbleibendem durchschnittlichem Betrag pro Zahlung:</p><div class="threshold-list">${switches.map(x=>`<div class="threshold"><span>Bei etwa ${chf(x.v)} Jahresumsatz</span><strong>${esc(x.o.name)}</strong></div>`).join('')}</div><p class="footnote">Grobe Stichproben, keine exakten Schwellenwerte. Zwischen den gezeigten Umsätzen können weitere Wechsel liegen.</p>`;
$('print-basis').textContent=`Kartenumsatz ${chf(c.volume)} / Jahr · ${fmt(c.tx)} Kartenzahlungen / Jahr · Betrachtung ${c.years} Jahr(e) · Durchschnittsbetrag ${chf(c.volume/c.tx)}${current.some(o=>o.model==='icpp')?' · Kartenmix: '+mix.map(m=>`${m.name} ${m.share} %; Interchange ${m.ic} %, Netzwerk ${m.scheme} %`).join(' | '):''}`;
$('limits').textContent=`Stand ${new Intl.DateTimeFormat('de-CH').format(new Date())}. ${demo?'Beispielwerte – keine verbindlichen Nexi- oder Wettbewerbskonditionen. ':''}Indikative Berechnung ohne MwSt., Chargebacks, Rückerstattungen, FX, DCC, PCI und nicht erfasste Sonderleistungen. IC++-Gebühren beruhen auf anpassbaren Annahmen. Vertragsbedingungen und Kartenmix vor Weitergabe prüfen.`;}
function switchMode(next){mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('mode-help').textContent=mode==='internal2'?'Trage die Konditionen der beiden Nexi-Optionen ein.':mode==='internal3'?'Vergleiche drei Nexi-Propositionen miteinander.':'Trage eine Nexi-Offerte und die Offerte des Wettbewerbers ein.';renderOffers();calculate();}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));$('demo').onclick=()=>{Object.assign(nexi[0],{rate:'1.25',txFee:'0.05',rent:'25'});Object.assign(nexi[1],{rate:'1.48',txFee:'0.05',rent:'0'});Object.assign(nexi[2],{rate:'0.48',txFee:'0.05',rent:'25'});Object.assign(competitor,{rate:'1.42',txFee:'0.08',rent:'28'});demo=true;renderOffers();calculate();$('demo').textContent='Beispiel geladen';};$('print').onclick=()=>{document.querySelectorAll('.result-details').forEach(d=>d.open=true);window.print();};['volume','tx'].forEach(id=>$(id).addEventListener('input',e=>{const input=e.target,before=input.value.slice(0,input.selectionStart).replace(/\D/g,'').length,digits=input.value.replace(/\D/g,'');input.value=digits.replace(/\B(?=(\d{3})+(?!\d))/g,'’');let pos=0,seen=0;while(pos<input.value.length&&seen<before){if(/\d/.test(input.value[pos]))seen++;pos++;}input.setSelectionRange(pos,pos);calculate();}));$('years').oninput=calculate;renderMix();switchMode('internal2');
})();
