(()=>{'use strict';
const $=id=>document.getElementById(id),fmt=(n,d=0)=>new Intl.NumberFormat('de-CH',{minimumFractionDigits:d,maximumFractionDigits:d}).format(n),chf=n=>`CHF ${fmt(n,2)}`,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),n=v=>v!==''&&Number.isFinite(+v)&&+v>=0?+v:null;
let seq=0,demo=false;
const mix=[{name:'CH Debit Consumer',share:'65',ic:'0.20',scheme:'0.12'},{name:'CH Credit Consumer',share:'25',ic:'0.40',scheme:'0.15'},{name:'Europa Consumer',share:'7',ic:'0.65',scheme:'0.30'},{name:'Ausland / Business',share:'3',ic:'1.50',scheme:'0.70'}];
const make=(name,provider='Nexi',model='blended')=>({id:++seq,name,provider,model,rate:'',txFee:'0',rent:'0',terminals:'1',monthly:'0',annual:'0',setup:'0',minimum:'0',surcharge:'0'});
let offers=[make('Standard mit Terminal'),make('Ohne Terminalmiete'),make('Verbandskonditionen','Nexi','icpp')];
const field=(label,key,value,unit,step='0.01')=>`<label>${label}<span class="control"><input data-key="${key}" type="number" min="0" step="${step}" inputmode="decimal" value="${esc(value)}"><b>${unit}</b></span></label>`;
function renderMix(){ $('mix').innerHTML=mix.map((m,i)=>`<div class="mix-row"><strong>${esc(m.name)}</strong>${field('Umsatzanteil',`share:${i}`,m.share,'%','0.1')}${field('Interchange',`ic:${i}`,m.ic,'%','0.001')}${field('Scheme Fee',`scheme:${i}`,m.scheme,'%','0.001')}</div>`).join('');$('mix').oninput=e=>{let [key,i]=(e.target.dataset.key||'').split(':');if(key){mix[+i][key]=e.target.value;demo=false;calculate();}};}
function renderOffers(){ $('offers').innerHTML=offers.map((o,i)=>`<article class="offer" data-id="${o.id}"><div class="offer-top"><span class="offer-number">${String(i+1).padStart(2,'0')}</span><button class="remove" data-action="remove" type="button">Entfernen</button></div><label>Name<input class="plain" data-key="name" maxlength="60" value="${esc(o.name)}"></label><div class="fields"><label>Anbieter<select data-key="provider"><option ${o.provider==='Nexi'?'selected':''}>Nexi</option><option ${o.provider==='Wettbewerber'?'selected':''}>Wettbewerber</option></select></label><label>Preismodell<select data-key="model"><option value="blended" ${o.model==='blended'?'selected':''}>Blended</option><option value="icpp" ${o.model==='icpp'?'selected':''}>IC++</option></select></label></div><div class="fields">${field(o.model==='icpp'?'Acquirer Markup':'Blended Disagio','rate',o.rate,'%','0.001')}${field('Fixgebühr je Transaktion','txFee',o.txFee,'CHF')}</div><p class="subtle">${o.model==='icpp'?'Interchange und Scheme Fees aus dem gemeinsamen Kartenmix werden ergänzt.':'Basis-Disagio inklusive Interchange und Scheme Fees; zusätzliche Zuschläge separat.'}</p><details class="cost-details"><summary>Terminal & weitere Kosten</summary><div class="fields">${field('Miete je Terminal / Monat','rent',o.rent,'CHF')}${field('Anzahl Terminals','terminals',o.terminals,'Stk.','1')}${field('Weitere Monatskosten','monthly',o.monthly,'CHF')}${field('Weitere Jahreskosten','annual',o.annual,'CHF')}${field('Einmalige Einrichtung','setup',o.setup,'CHF')}${field('Zusätzlicher variabler Zuschlag','surcharge',o.surcharge,'%','0.001')}${field('Mindestgebühr Acquiring / Monat','minimum',o.minimum,'CHF')}</div><p class="subtle">Mindestgebühr ersetzt tiefere Acquiring-Kosten. Zuschläge nur erfassen, wenn sie zusätzlich anfallen.</p></details><div class="offer-total" id="total-${o.id}">Konditionen ergänzen</div></article>`).join('');$('offers').querySelectorAll('.offer').forEach(card=>{const o=offers.find(x=>x.id===+card.dataset.id);card.addEventListener('input',e=>{if(e.target.dataset.key){o[e.target.dataset.key]=e.target.value;demo=false;calculate();}});card.addEventListener('change',e=>{if(e.target.dataset.key){o[e.target.dataset.key]=e.target.value;if(e.target.dataset.key==='model')renderOffers();demo=false;calculate();}});card.querySelector('[data-action="remove"]').onclick=()=>{if(offers.length<=2)return;offers=offers.filter(x=>x!==o);renderOffers();calculate();};});}
function cost(o,c,v=c.volume){const tx=v*c.tx/c.volume,acquiring=v*(+o.rate+(o.model==='icpp'?c.pass*100:0))/100+tx*+o.txFee,minimum=Math.max(0,+o.minimum*12-acquiring),surcharge=v*+o.surcharge/100,terminal=12*+o.rent*+o.terminals,other=12*+o.monthly+(+o.annual),once=+o.setup/c.years;return {acquiring,minimum,surcharge,terminal,other,once,total:acquiring+minimum+surcharge+terminal+other+once};}
function calculate(){const c={volume:n($('volume').value),tx:n($('tx').value),years:n($('years').value)},share=mix.reduce((s,m)=>s+(n(m.share)||0),0);c.pass=mix.reduce((s,m)=>s+(n(m.share)||0)/100*((n(m.ic)||0)+(n(m.scheme)||0))/100,0);c.mixValid=Math.abs(share-100)<.001&&mix.every(m=>['share','ic','scheme'].every(k=>n(m[k])!==null));$('mix-status').textContent=`${fmt(share,1)} % erfasst`;$('mix-error').textContent=c.mixValid?'':'Umsatzanteile müssen 100 % ergeben und alle Sätze ausgefüllt sein.';$('ticket').textContent=c.volume>0&&c.tx>0?`Durchschnittlicher Bon: ${chf(c.volume/c.tx)}`:'';
const keys=['rate','txFee','rent','terminals','monthly','annual','setup','minimum','surcharge'];const valid=c.volume>0&&c.tx>0&&Number.isInteger(c.tx)&&Number.isInteger(c.years)&&c.years>=1&&c.years<=10&&(!offers.some(o=>o.model==='icpp')||c.mixValid)&&offers.every(o=>o.name.trim()&&keys.every(k=>n(o[k])!==null)&&Number.isInteger(+o.terminals));$('message').hidden=valid;$('result').hidden=!valid;$('print').disabled=!valid;if(!valid){$('message').textContent='Bitte Umsatz, Transaktionen und Konditionen aller Angebote ergänzen. Bei IC++ muss der Kartenmix 100 % ergeben.';offers.forEach(o=>{$(`total-${o.id}`).textContent='Konditionen ergänzen';});return;}
$('print-basis').textContent=`Basis: ${chf(c.volume)} Kartenumsatz / Jahr · ${fmt(c.tx)} Transaktionen / Jahr · ${c.years} Jahr(e) Betrachtung · durchschnittlicher Bon ${chf(c.volume/c.tx)} · IC++-Kartenmix: ${mix.map(m=>m.name+' '+m.share+' % (IC '+m.ic+' %, Scheme '+m.scheme+' %)').join('; ')}`;const ranked=offers.map(o=>({...o,r:cost(o,c)})).sort((a,b)=>a.r.total-b.r.total);ranked.forEach(o=>{$(`total-${o.id}`).innerHTML=`<small>Geschätzte Jahreskosten</small><strong>${chf(o.r.total)}</strong>`;});$('winner').textContent=ranked[0].name;$('saving').textContent=`${ranked[0].provider} · ${chf(ranked[0].r.total)} / Jahr · ${chf(ranked[1].r.total-ranked[0].r.total)} weniger als die nächstgünstige erfasste Option`;
const max=Math.max(1,...ranked.map(o=>o.r.total));$('ranking').innerHTML=ranked.map((o,i)=>`<div class="rank"><div class="rank-line"><div><b>${i+1}. ${esc(o.name)}</b><small>${o.provider} · ${o.model==='icpp'?'IC++':'Blended'}</small></div><strong>${chf(o.r.total)} / Jahr</strong></div><div class="bar-bg"><div class="bar ${i?'secondary':''}" style="width:${Math.max(2,o.r.total/max*100)}%"></div></div>${i?`<small>+ ${chf(o.r.total-ranked[0].r.total)} zum günstigsten Angebot</small>`:''}</div>`).join('');
const vals=[.25,.5,.75,1,1.5,2,3,5].map(k=>Math.max(1000,Math.round(c.volume*k/1000)*1000)),changes=vals.map(v=>({v,o:[...offers].sort((a,b)=>cost(a,c,v).total-cost(b,c,v).total)[0]})).filter((x,i,a)=>!i||x.o.id!==a[i-1].o.id);$('thresholds').innerHTML=`<h3>Umsatz-Szenarien</h3><p class="subtle">Bonhöhe und Kartenmix bleiben gleich; Transaktionen skalieren mit dem Umsatz.</p><div class="threshold-list">${changes.map((x,i)=>`<div class="threshold"><span>${i?'Ab':'Bei'} ca. ${chf(x.v)} Jahresumsatz</span><strong>${esc(x.o.name)}</strong></div>`).join('')}</div><p class="footnote">Stichproben von 25–500 % des Umsatzes, keine exakten Break-even-Punkte. Weitere Wechsel zwischen Stichproben möglich.</p>`;
$('breakdown').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Pro Jahr</th>${ranked.map(o=>`<th>${esc(o.name)}</th>`).join('')}</tr></thead><tbody>${[['Acquiring inkl. Tx','acquiring'],['Mindestgebühr (Aufpreis)','minimum'],['Variable Zuschläge','surcharge'],['Terminalmiete','terminal'],['Weitere laufende Kosten','other'],['Einrichtung, anteilig','once'],['Gesamt','total']].map(([name,k])=>`<tr><td>${name}</td>${ranked.map(o=>`<td>${chf(o.r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
$('limits').textContent=`Stand ${new Intl.DateTimeFormat('de-CH').format(new Date())} · ${c.years} Jahr(e), Einrichtung anteilig. ${demo?'DEMO-WERTE; keine verbindlichen Tarife. ':''}Ohne MwSt., Chargebacks, Refunds, FX, DCC, PCI und nicht erfasste Sonderleistungen. Die Kostenaussage hängt vom Kartenmix und den tatsächlichen Verträgen ab. Geräte, Support, Service und Vertragsbedingungen separat bewerten.`;}
$('add').onclick=()=>{offers.push(make('Neues Angebot','Wettbewerber'));renderOffers();calculate();};$('demo').onclick=()=>{Object.assign(offers[0],{rate:'1.25',txFee:'0.05',rent:'25'});Object.assign(offers[1],{rate:'1.48',txFee:'0.05',rent:'0'});Object.assign(offers[2],{rate:'0.48',txFee:'0.05',rent:'25'});demo=true;renderOffers();calculate();$('demo').textContent='Demo geladen';};$('print').onclick=()=>window.print();['volume','tx','years'].forEach(id=>$(id).oninput=calculate);renderMix();renderOffers();calculate();
})();
